import numpy as np


qwerty_coords = dict()
qwerty_coords['ё'] = np.array([0, 0], dtype=np.int32)
qwerty_coords['й'] = np.array([0, 0], dtype=np.int32)
qwerty_coords['ц'] = np.array([0, 1], dtype=np.int32)
qwerty_coords['у'] = np.array([0, 2], dtype=np.int32)
qwerty_coords['к'] = np.array([0, 3], dtype=np.int32)
qwerty_coords['е'] = np.array([0, 4], dtype=np.int32)
qwerty_coords['н'] = np.array([0, 5], dtype=np.int32)
qwerty_coords['г'] = np.array([0, 6], dtype=np.int32)
qwerty_coords['ш'] = np.array([0, 7], dtype=np.int32)
qwerty_coords['щ'] = np.array([0, 8], dtype=np.int32)
qwerty_coords['з'] = np.array([0, 9], dtype=np.int32)
qwerty_coords['х'] = np.array([0, 10], dtype=np.int32)
qwerty_coords['ъ'] = np.array([0, 11], dtype=np.int32)

qwerty_coords['ф'] = np.array([1, 0], dtype=np.int32)
qwerty_coords['ы'] = np.array([1, 1], dtype=np.int32)
qwerty_coords['в'] = np.array([1, 2], dtype=np.int32)
qwerty_coords['а'] = np.array([1, 3], dtype=np.int32)
qwerty_coords['п'] = np.array([1, 4], dtype=np.int32)
qwerty_coords['р'] = np.array([1, 5], dtype=np.int32)
qwerty_coords['о'] = np.array([1, 6], dtype=np.int32)
qwerty_coords['л'] = np.array([1, 7], dtype=np.int32)
qwerty_coords['д'] = np.array([1, 8], dtype=np.int32)
qwerty_coords['ж'] = np.array([1, 9], dtype=np.int32)
qwerty_coords['э'] = np.array([1, 10], dtype=np.int32)

qwerty_coords['я'] = np.array([2, 0], dtype=np.int32)
qwerty_coords['ч'] = np.array([2, 1], dtype=np.int32)
qwerty_coords['с'] = np.array([2, 2], dtype=np.int32)
qwerty_coords['м'] = np.array([2, 3], dtype=np.int32)
qwerty_coords['и'] = np.array([2, 4], dtype=np.int32)
qwerty_coords['т'] = np.array([2, 5], dtype=np.int32)
qwerty_coords['ь'] = np.array([2, 6], dtype=np.int32)
qwerty_coords['б'] = np.array([2, 7], dtype=np.int32)
qwerty_coords['ю'] = np.array([2, 8], dtype=np.int32)

